/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class CustomerEngagement202502CreateCustomEngagementTaskRequestBodyCustomMessage {
    /**
    * The message body. - Valid format: plain text, unicode emoji (UTF-8) - Valid length:  [1, 500]
    */
    'body'?: string;
    /**
    * The message title.  - Valid format: plain text, unicode emoji (UTF-8) - Valid length: [1, 70]
    */
    'title'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "body",
            "baseName": "body",
            "type": "string"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CustomerEngagement202502CreateCustomEngagementTaskRequestBodyCustomMessage.attributeTypeMap;
    }
}

