/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { CustomerEngagement202502CreateCustomEngagementTaskRequestBodyCustomMessage } from './CreateCustomEngagementTaskRequestBodyCustomMessage';

export class CustomerEngagement202502CreateCustomEngagementTaskRequestBody {
    /**
    * The engagement channel. Only `TIKTOK_IM` is supported. 
    */
    'channel'?: string;
    /**
    * The coupon IDs that you want to include as interactive cards in the message.  Max count: 1 You can only add coupons that have one of these sets of property: - `coupons.display_type=REGULAR` and `coupons.target_buyer_segment=ALL` - `coupons.display_type=REGULAR` and `coupons.target_buyer_segment=REPEAT_CUSTOMERS`. Find out the coupon ID and properties from the [Search Coupons API](https://partner.tiktokshop.com/docv2/page/6699dcdf115ebe02f841e4cd).
    */
    'couponIds'?: Array<string>;
    'customMessage'?: CustomerEngagement202502CreateCustomEngagementTaskRequestBodyCustomMessage;
    /**
    * The time at which the task ends, and messages will no longer be sent. Unix timestamp (seconds).
    */
    'endTime'?: number;
    /**
    * The product IDs that you want to include as interactive cards in the message. Retrieve this value from the [Search Products API](https://partner.tiktokshop.com/docv2/page/65854ffb8f559302d8a6acda). Max count: 4
    */
    'productIds'?: Array<string>;
    /**
    * The name of the task. 
    */
    'taskName'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "channel",
            "baseName": "channel",
            "type": "string"
        },
        {
            "name": "couponIds",
            "baseName": "coupon_ids",
            "type": "Array<string>"
        },
        {
            "name": "customMessage",
            "baseName": "custom_message",
            "type": "CustomerEngagement202502CreateCustomEngagementTaskRequestBodyCustomMessage"
        },
        {
            "name": "endTime",
            "baseName": "end_time",
            "type": "number"
        },
        {
            "name": "productIds",
            "baseName": "product_ids",
            "type": "Array<string>"
        },
        {
            "name": "taskName",
            "baseName": "task_name",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CustomerEngagement202502CreateCustomEngagementTaskRequestBody.attributeTypeMap;
    }
}

