/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { CustomerEngagement202502GetFeaturePermissionsResponseDataFeatures } from './GetFeaturePermissionsResponseDataFeatures';

export class CustomerEngagement202502GetFeaturePermissionsResponseData {
    /**
    * The list of customer engagement features that has access control.
    */
    'features'?: Array<CustomerEngagement202502GetFeaturePermissionsResponseDataFeatures>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "features",
            "baseName": "features",
            "type": "Array<CustomerEngagement202502GetFeaturePermissionsResponseDataFeatures>"
        }    ];

    static getAttributeTypeMap() {
        return CustomerEngagement202502GetFeaturePermissionsResponseData.attributeTypeMap;
    }
}

