/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class CustomerEngagement202502GetFeaturePermissionsResponseDataFeatures {
    /**
    * A flag to indicate whether the shop has permission to use this feature. Possible values: - `true`: Authorized to use this feature. - `false`: Not authorized to use this feature.
    */
    'isAuthorized'?: boolean;
    /**
    * The feature name. Possible values: - `FUNDAMENTAL`: The ability to use any customer engagement APIs or features. This is the prerequisite for all other customer engagement features. - `CUSTOM_MSG`: The ability to define and send custom messages.
    */
    'name'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "isAuthorized",
            "baseName": "is_authorized",
            "type": "boolean"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CustomerEngagement202502GetFeaturePermissionsResponseDataFeatures.attributeTypeMap;
    }
}

