/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class CustomerEngagement202412CreateEngagementTaskRequestBody {
    /**
    * The engagement channel. Only `TIKTOK_IM` is supported.
    */
    'channel'?: string;
    /**
    * The coupon ID. Retrieve this value and other coupon-related information from the [Search Coupons API](https://partner.tiktokshop.com/docv2/page/6699dcdf115ebe02f841e4cd).  **Note**: The coupon properties must comply with the rules defined in `coupon_card_rules.coupon_type` of the [Get Message Templates API](67777e44223fde02fdfdc157).
    */
    'couponIds'?: Array<string>;
    /**
    * The time at which the task ends, and messages will no longer be sent. Unix timestamp (seconds).
    */
    'endTime'?: number;
    /**
    * The product ID. Retrieve this value from the [Search Products API](https://partner.tiktokshop.com/docv2/page/65854ffb8f559302d8a6acda).
    */
    'productIds'?: Array<string>;
    /**
    * The name of the task.
    */
    'taskName'?: string;
    /**
    * The ID of engagement message templates predefined by TikTok Shop. Retrieve the value from [Get Message Templates](67777e44223fde02fdfdc157).
    */
    'templateId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "channel",
            "baseName": "channel",
            "type": "string"
        },
        {
            "name": "couponIds",
            "baseName": "coupon_ids",
            "type": "Array<string>"
        },
        {
            "name": "endTime",
            "baseName": "end_time",
            "type": "number"
        },
        {
            "name": "productIds",
            "baseName": "product_ids",
            "type": "Array<string>"
        },
        {
            "name": "taskName",
            "baseName": "task_name",
            "type": "string"
        },
        {
            "name": "templateId",
            "baseName": "template_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CustomerEngagement202412CreateEngagementTaskRequestBody.attributeTypeMap;
    }
}

