/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { CustomerEngagement202412GetMessageTemplatesResponseDataMessageTemplates } from './GetMessageTemplatesResponseDataMessageTemplates';

export class CustomerEngagement202412GetMessageTemplatesResponseData {
    /**
    * Customer engagement message templates predefined by TikTok Shop.
    */
    'messageTemplates'?: Array<CustomerEngagement202412GetMessageTemplatesResponseDataMessageTemplates>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "messageTemplates",
            "baseName": "message_templates",
            "type": "Array<CustomerEngagement202412GetMessageTemplatesResponseDataMessageTemplates>"
        }    ];

    static getAttributeTypeMap() {
        return CustomerEngagement202412GetMessageTemplatesResponseData.attributeTypeMap;
    }
}

