/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { CustomerEngagement202412GetMessageTemplatesResponseDataMessageTemplatesCouponCardRules } from './GetMessageTemplatesResponseDataMessageTemplatesCouponCardRules';
import { CustomerEngagement202412GetMessageTemplatesResponseDataMessageTemplatesProductCardRules } from './GetMessageTemplatesResponseDataMessageTemplatesProductCardRules';

export class CustomerEngagement202412GetMessageTemplatesResponseDataMessageTemplates {
    'couponCardRules'?: CustomerEngagement202412GetMessageTemplatesResponseDataMessageTemplatesCouponCardRules;
    /**
    * The template ID.
    */
    'id'?: string;
    /**
    * The message body.
    */
    'messageBody'?: string;
    /**
    * The message title.
    */
    'messageTitle'?: string;
    'productCardRules'?: CustomerEngagement202412GetMessageTemplatesResponseDataMessageTemplatesProductCardRules;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "couponCardRules",
            "baseName": "coupon_card_rules",
            "type": "CustomerEngagement202412GetMessageTemplatesResponseDataMessageTemplatesCouponCardRules"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "messageBody",
            "baseName": "message_body",
            "type": "string"
        },
        {
            "name": "messageTitle",
            "baseName": "message_title",
            "type": "string"
        },
        {
            "name": "productCardRules",
            "baseName": "product_card_rules",
            "type": "CustomerEngagement202412GetMessageTemplatesResponseDataMessageTemplatesProductCardRules"
        }    ];

    static getAttributeTypeMap() {
        return CustomerEngagement202412GetMessageTemplatesResponseDataMessageTemplates.attributeTypeMap;
    }
}

