/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class CustomerEngagement202412GetMessageTemplatesResponseDataMessageTemplatesCouponCardRules {
    /**
    * The types of coupon that can be included in the message.  Possible values: - REGULAR_ALL: Regular coupons that target all buyers.  Required coupon properties: `coupons.display_type=REGULAR` and `coupons.target_buyer_segment=ALL` in the [Search Coupons API](https://partner.tiktokshop.com/docv2/page/6699dcdf115ebe02f841e4cd). - REGULAR_REPEAT: Regular coupons that target only repeat buyers.  Required coupon properties: `coupons.display_type=REGULAR` and `coupons.target_buyer_segment=REPEAT_CUSTOMERS` in the [Search Coupons API](https://partner.tiktokshop.com/docv2/page/6699dcdf115ebe02f841e4cd).
    */
    'couponType'?: Array<string>;
    /**
    * The maximum number of coupon cards that can be included.
    */
    'maxCount'?: number;
    /**
    * The minimum number of coupon cards that must be included.
    */
    'minCount'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "couponType",
            "baseName": "coupon_type",
            "type": "Array<string>"
        },
        {
            "name": "maxCount",
            "baseName": "max_count",
            "type": "number"
        },
        {
            "name": "minCount",
            "baseName": "min_count",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return CustomerEngagement202412GetMessageTemplatesResponseDataMessageTemplatesCouponCardRules.attributeTypeMap;
    }
}

