/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class CustomerEngagement202412GetMessageTemplatesResponseDataMessageTemplatesProductCardRules {
    /**
    * The maximum number of product cards that can be included.
    */
    'maxCount'?: number;
    /**
    * The minimum number of product cards that must be included.
    */
    'minCount'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "maxCount",
            "baseName": "max_count",
            "type": "number"
        },
        {
            "name": "minCount",
            "baseName": "min_count",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return CustomerEngagement202412GetMessageTemplatesResponseDataMessageTemplatesProductCardRules.attributeTypeMap;
    }
}

