/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class CustomerEngagement202412GetTaskPerformancesResponseDataTaskPerformances {
    /**
    * The number of coupons claimed.
    */
    'claimedCouponsCount'?: number;
    /**
    * The revenue from the converted orders.
    */
    'gmvAmount'?: string;
    /**
    * Task ID
    */
    'id'?: string;
    /**
    * The number of orders resulting from the message.
    */
    'orderCount'?: number;
    /**
    * The number of users that read the message.
    */
    'readRecipientCount'?: number;
    /**
    * The number of users that received the message.
    */
    'sentRecipientCount'?: number;
    /**
    * The status of the task. Possible values: SENDING FAILED CANCELED SUCCESS
    */
    'status'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "claimedCouponsCount",
            "baseName": "claimed_coupons_count",
            "type": "number"
        },
        {
            "name": "gmvAmount",
            "baseName": "gmv_amount",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "orderCount",
            "baseName": "order_count",
            "type": "number"
        },
        {
            "name": "readRecipientCount",
            "baseName": "read_recipient_count",
            "type": "number"
        },
        {
            "name": "sentRecipientCount",
            "baseName": "sent_recipient_count",
            "type": "number"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CustomerEngagement202412GetTaskPerformancesResponseDataTaskPerformances.attributeTypeMap;
    }
}

