/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class CustomerEngagement202412GetTaskPerformancesRequestBody {
    /**
    * The list of tasks for which you want to retrieve performance data.
    */
    'taskIds'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "taskIds",
            "baseName": "task_ids",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return CustomerEngagement202412GetTaskPerformancesRequestBody.attributeTypeMap;
    }
}

