/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { CustomerEngagement202412GetTaskPerformancesResponseDataTaskPerformances } from './GetTaskPerformancesResponseDataTaskPerformances';

export class CustomerEngagement202412GetTaskPerformancesResponseData {
    /**
    * The requested list of task performance.
    */
    'taskPerformances'?: Array<CustomerEngagement202412GetTaskPerformancesResponseDataTaskPerformances>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "taskPerformances",
            "baseName": "task_performances",
            "type": "Array<CustomerEngagement202412GetTaskPerformancesResponseDataTaskPerformances>"
        }    ];

    static getAttributeTypeMap() {
        return CustomerEngagement202412GetTaskPerformancesResponseData.attributeTypeMap;
    }
}

