/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { CustomerEngagement202412SendEngagementMessageResponseDataErrorsDetail } from './SendEngagementMessageResponseDataErrorsDetail';

export class CustomerEngagement202412SendEngagementMessageResponseDataErrors {
    /**
    * The error code.
    */
    'code'?: number;
    'detail'?: CustomerEngagement202412SendEngagementMessageResponseDataErrorsDetail;
    /**
    * The error message.
    */
    'message'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number"
        },
        {
            "name": "detail",
            "baseName": "detail",
            "type": "CustomerEngagement202412SendEngagementMessageResponseDataErrorsDetail"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CustomerEngagement202412SendEngagementMessageResponseDataErrors.attributeTypeMap;
    }
}

