/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { CustomerEngagement202412SendEngagementMessageResponseDataErrors } from './SendEngagementMessageResponseDataErrors';

export class CustomerEngagement202412SendEngagementMessageResponseData {
    /**
    * The list of errors that occurred.
    */
    'errors'?: Array<CustomerEngagement202412SendEngagementMessageResponseDataErrors>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "errors",
            "baseName": "errors",
            "type": "Array<CustomerEngagement202412SendEngagementMessageResponseDataErrors>"
        }    ];

    static getAttributeTypeMap() {
        return CustomerEngagement202412SendEngagementMessageResponseData.attributeTypeMap;
    }
}

