/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class CustomerEngagement202412SendEngagementMessageRequestBody {
    /**
    * The anonymized email address of the buyer. Retrieve this value from the [Get Order Details API](650aa8ccc16ffe02b8f167a0). **Note**: You can only send messages to buyers who have placed at least one order with the shop in the past 365 days.
    */
    'buyerEmails'?: Array<string>;
    /**
    * The ID of the associated customer engagement task. Use the value returned when you call the [Create Engagement Task API](67777e436b61b002f60f01da). **Note**: Ensure the task is still active. You cannot send messages to tasks that have ended.
    */
    'taskId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "buyerEmails",
            "baseName": "buyer_emails",
            "type": "Array<string>"
        },
        {
            "name": "taskId",
            "baseName": "task_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CustomerEngagement202412SendEngagementMessageRequestBody.attributeTypeMap;
    }
}

