/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Product202601ProductAuditingResearchResponseDataProductsCategories {
    /**
    * category id
    */
    'id'?: string;
    /**
    * is leaf category
    */
    'isLeaf'?: boolean;
    /**
    * category level
    */
    'level'?: number;
    /**
    * category name
    */
    'name'?: string;
    /**
    * parent category id
    */
    'parentId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "isLeaf",
            "baseName": "is_leaf",
            "type": "boolean"
        },
        {
            "name": "level",
            "baseName": "level",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "parentId",
            "baseName": "parent_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Product202601ProductAuditingResearchResponseDataProductsCategories.attributeTypeMap;
    }
}

