/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Product202601ProductAuditingResearchRequestBody {
    /**
    * brand id
    */
    'brandIds'?: Array<string>;
    /**
    * leaf category id
    */
    'categoryIds'?: Array<string>;
    /**
    * max is 20
    */
    'productIds'?: Array<string>;
    /**
    * product title
    */
    'productTitle'?: string;
    /**
    * shop id
    */
    'sellerId'?: string;
    /**
    * shop name
    */
    'sellerName'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "brandIds",
            "baseName": "brand_ids",
            "type": "Array<string>"
        },
        {
            "name": "categoryIds",
            "baseName": "category_ids",
            "type": "Array<string>"
        },
        {
            "name": "productIds",
            "baseName": "product_ids",
            "type": "Array<string>"
        },
        {
            "name": "productTitle",
            "baseName": "product_title",
            "type": "string"
        },
        {
            "name": "sellerId",
            "baseName": "seller_id",
            "type": "string"
        },
        {
            "name": "sellerName",
            "baseName": "seller_name",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Product202601ProductAuditingResearchRequestBody.attributeTypeMap;
    }
}

