/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Product202601ProductAuditingResearchResponseDataProductsCategories } from './ProductAuditingResearchResponseDataProductsCategories';
import { Product202601ProductAuditingResearchResponseDataProductsVariants } from './ProductAuditingResearchResponseDataProductsVariants';

export class Product202601ProductAuditingResearchResponseDataProducts {
    /**
    * brand id
    */
    'brandId'?: string;
    /**
    * brand name
    */
    'brandName'?: string;
    /**
    * The category tree information of the source product included in the virtual bundle.
    */
    'categories'?: Array<Product202601ProductAuditingResearchResponseDataProductsCategories>;
    /**
    * sale region eg. DE, IT, FR, ES, IE
    */
    'country'?: string;
    /**
    * The product description in HTML format.
    */
    'description'?: string;
    /**
    * The product ID generated by TikTok Shop.
    */
    'id'?: string;
    /**
    * PDP URL
    */
    'listingUrl'?: string;
    /**
    * The URLs to view the images.
    */
    'mainImageUrls'?: Array<string>;
    /**
    * shop id
    */
    'sellerId'?: string;
    /**
    * shop name
    */
    'sellerName'?: string;
    /**
    * The product title.
    */
    'title'?: string;
    /**
    * A list of Stock Keeping Units (SKUs) used to identify distinct variants of the product.
    */
    'variants'?: Array<Product202601ProductAuditingResearchResponseDataProductsVariants>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "brandId",
            "baseName": "brand_id",
            "type": "string"
        },
        {
            "name": "brandName",
            "baseName": "brand_name",
            "type": "string"
        },
        {
            "name": "categories",
            "baseName": "categories",
            "type": "Array<Product202601ProductAuditingResearchResponseDataProductsCategories>"
        },
        {
            "name": "country",
            "baseName": "country",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "listingUrl",
            "baseName": "listing_url",
            "type": "string"
        },
        {
            "name": "mainImageUrls",
            "baseName": "main_image_urls",
            "type": "Array<string>"
        },
        {
            "name": "sellerId",
            "baseName": "seller_id",
            "type": "string"
        },
        {
            "name": "sellerName",
            "baseName": "seller_name",
            "type": "string"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "variants",
            "baseName": "variants",
            "type": "Array<Product202601ProductAuditingResearchResponseDataProductsVariants>"
        }    ];

    static getAttributeTypeMap() {
        return Product202601ProductAuditingResearchResponseDataProducts.attributeTypeMap;
    }
}

