/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Fulfillment202601RedeemInfoCallbackRequestBodyOrderInfoListRedeemInfo {
    /**
    * Redeem type is \'CODE\', set redeem code to this field. Redeem type is \'URL\', set redeem url to this field. The maximum number of characters is 1000.
    */
    'redeemData'?: string;
    /**
    * What redeem type that you callback. \'CODE\' - type code \'URL\' - type url
    */
    'redeemType'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "redeemData",
            "baseName": "redeem_data",
            "type": "string"
        },
        {
            "name": "redeemType",
            "baseName": "redeem_type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Fulfillment202601RedeemInfoCallbackRequestBodyOrderInfoListRedeemInfo.attributeTypeMap;
    }
}

